SUBROUTINE WSTAT(A,N,SUM,AVE,VAR,SD)
DIMENSION A(N)
    SUM=0.0
    DO I=1,N
        SUM=SUM+A(I)
    END DO
    AVE=SUM/N
    SUMS=0.0
    DO I=1,N
        SUMS=SUMS+(A(I)-AVE)**2
    END DO
    VAR=SUMS/N
    SD=SQRT(VAR)
    RETURN
END SUBROUTINE

!MAIN PROGRAM
DIMENSION A(100)
PRINT*,"HOW MANY ARRAY ELEMENTS?"
READ*,N
PRINT*,"INPUT ELEMENTS"
DO I=1,N
    READ*,A(I)
END DO
CALL WSTAT(A,N,SUM,AVE,VAR,STD)
PRINT*,"SD",STD
PRINT*,"VAR:",VAR
PRINT*,"MEAN:",AVE
PRINT*,"SUM:",SUM
STOP
END

