!FUNCTION SUBPROGRAM
FUNCTION AMEAN(X,N)
    DIMENSION X(N)
    SUM=0.0
    DO I=1,N
        SUM=SUM+X(I)
    END DO
    AMEAN=SUM/N
    RETURN
    END

FUNCTION GMEAN(X,N)
    DIMENSION X(N)
    PROD=1
    DO I=1,N
        PROD=PROD*X(I)
    END DO
    GMEAN=(PROD)**(1.0/N)
    RETURN
    END

!MAIN PROGRAM
REAL MEAN
DIMENSION A(100)
PRINT*,"HOW MANY ELEMENTS IN THE ARRAY?"
READ*,NU
DO I=1,NU
    READ*,A(I)
END DO
MEAN=AMEAN(A,NU)
GEMEAN=GMEAN(A,NU)
PRINT*,"ARITHMETIC MEAN:",MEAN
PRINT*,"GEOMETRIC MEAN:",GEMEAN
STOP
END
