FUNCTION IFACT(K)
    IFACT=1
    IF(K.EQ.0)RETURN 
DO I=1,K
   IFACT=IFACT*I 
END DO
RETURN
END

!MAIN PROGRAM
PROGRAM MAIN
    PRINT*,"PUT N AND I:"
    READ*,N,I 
    IF(I.GT.N)GOTO 10
    IBINC=(IFACT(N)/(IFACT(I)*IFACT(N-I)))
    PRINT*,"BINOMIAL COEFFICIENT IS:",IBINC
10  STOP
END PROGRAM

