INTEGER A,BIG,ROW
DIMENSION A(10,3)
!READ IN ELEMENTS OF FIRST COLUMN
DO J=1,10
    READ*,A(J,1)
END DO
ROW=1
BIG=ABS(A(1,1))
DO J=1,10
    IF(ABS(A(J,1)).GT.BIG)THEN
        BIG=ABS(A(J,1))
        ROW=J
    END IF
END DO
PRINT*,"LARGEST VALUE:",BIG,"IS IN ROW:",ROW,"OF COLUMN 1"

STOP
END