PROGRAM FACTORIAL
    IMPLICIT NONE
    INTEGER:: I,N,FACT
    FACT=1
    WRITE(*,*)"FOR WHICH NUMBER YOU WANT THE FACTORIAL?"
    READ(*,*),N
    DO 10 I=1,N,1
        FACT=FACT*I
        10 CONTINUE
        WRITE(*,40)FACT
40  FORMAT(1X,I20)
END PROGRAM
