FUNCTION IFIBONACCI(K)
    INTEGER T1,T2,NT
    IFIBONACCI=0
    IF(K.EQ.0)RETURN
    IFIBONACCI=1
    IF(K.EQ.1)RETURN
    IFIBONACCI=1
    IF(K.EQ.2)RETURN
    T1=1
    T2=1
    DO I=3,K
        NT=T1+T2
        T1=T2
        T2=NT
        IFIBONACCI=T2
    END DO
RETURN 
END 

    INTEGER A
    PRINT*,"WHICH FIBONACCI NUMBER?"
    READ*,A
    PRINT*,"FIBONACCI",A,"IS:",IFIBONACCI(A)
    STOP
    END
