PROGRAM ODDEVEN
    READ(*,*)N
    DIVISOR=(N/2)*2
    IF(N.EQ.DIVISOR) GOTO 20
    IF(N.NE.DIVISOR) GOTO 30

    20  PRINT*,"EVEN NUMBER"
        STOP

    30  PRINT*,"ODD NUMBER"
        STOP

END PROGRAM
