PROGRAM QUADRATIC
    !COMPUTE REAL ROOTS OF A QUADRATIC EQUATION WHERE A IS NOT ZERO

    READ*, A,B,C
    D= B**2-4.0*A*C

    !TEST THE DISCRIMINANT
    !ARITHMETIC IF STATEMENT

    IF(D)22,33,44

22  PRINT*,"NO REAL ROOTS"

33  ROOT=-B/(2.0*A)
    PRINT*,"TWO EQUAL REAL ROOTS ARE, ",ROOT

44  ROOT1=(-B+SQRT(D))/(2.0*A)
    ROOT2=(-B-SQRT(D))/(2.0*A)
    PRINT*,"TWO DISTINCT REAL ROOTS ARE", ROOT1,"  &  ",ROOT2

END PROGRAM
