PROGRAM PI_VALUE
    !THIS PROGRAM CALCULATES PI BY THE BASAL PROBLEM
    SUM=0.0
    DO 10   I=1,1000
            SUM=SUM+(1.0/I**2)
    10 CONTINUE
    PRINT*,"APPROXIMATED VALUE OF PI IS:",SQRT(SUM*6.0)
    STOP
END PROGRAM
