PROGRAM EVERY_YEAR_DEPOSIT
    INTEGER YEAR
    DEPOSIT=500.0
    AMOUNT=0.0
    YEAR=1
    PRINT*,'YEAR  ','AMOUNT'
10  AMOUNT=AMOUNT+DEPOSIT
    AMOUNT=AMOUNT+AMOUNT*0.07

    PRINT*,YEAR ,AMOUNT
    YEAR=YEAR+1
    IF(YEAR.LE.10)GOTO 10

    STOP
END PROGRAM