PROGRAM PYTHAGOREAN_TRIPLET_1
    
    INTEGER A,B,C
    PRINT*,"VALUE OF A,B,C?"
    READ*,A,B,C
    IF(A.GE.25.OR.B.GE.25)GOTO 400
    IF(A.LT.B.AND.B.LT.C) GOTO 500

500 DO 100 I=1,A
        DO 200 J=1,B
            DO 300 K=1,C 
                !I,J,K REPRESENTS CURRENT VALUE OF A,B,C IN THE LOOP
                IF(I**2+J**2.EQ.K**2)PRINT*,"PYTHAGOREAN TRIPLET IS",I,J,K
            300 CONTINUE
        200 CONTINUE
    100 CONTINUE
    STOP

400 PRINT*,"A,B MUST BE LESS THEN 25"

STOP
END PROGRAM
    