PROGRAM PYTHAGOREAN_TRIPLET_2
    INTEGER A,B,C
    PRINT*,"VALUE OF C?"
    READ*,J !HOW FAR C GOES

    DO 100 A=1,24
        DO 200 B=1,24
            DO 300 C=1,J
                IF(A**2+B**2.EQ.C**2)PRINT*,"PYTHAGOREAN TRIPLET IS:",A,B,C
            300 CONTINUE
        200 CONTINUE
    100 CONTINUE

    STOP
END PROGRAM