PROGRAM PI_VALUE_REVERSE
    !THIS PROGRAM CALCULATES PI BY THE BASAL PROBLEM
    SUM=0.0
    DO 10   I=1,1000
            X=1001-I
            SUM=SUM+(1.0/X**2)
    10 CONTINUE
    PRINT*,"APPROXIMATED VALUE OF PI IN REVERSE IS:",SQRT(SUM*6.0)
    STOP
END PROGRAM
