PROGRAM STUDENT_COUNT_GREATER_90
    INTEGER SCORE
    PRINT*,"HOW MANY STUDENTS ARE IN THE CLASS?"
    READ*,L

    K=0         !COUNTER FOR STUDENT NUMBER
    N=0         !COUNTER FOR NUMBERS OVER 90

    I=1         !LOOP VARIABLE
    PRINT*,'GIVE SCORES:'
10  READ*,SCORE
    IF(SCORE.GE.0)K=K+1
    IF(SCORE.GE.90)N=N+1
    I=I+1
    IF(I.LE.L)GOTO 10

    PRINT*,"NO. OF STUDENTS ATTENDED : ",K
    PRINT*,"NO. OF STUDENTS WHO GOT>=90 : ",N
    STOP

END PROGRAM

