PROGRAM DIVISIBLE
PRINT*,'UP TO WHICH NUMBER?'
READ*,N
PRINT*,'OMIT DIVISIBLE BY WHICH NUMBER?'
READ*,L

I=1
10  IF(MOD(I,L).EQ.0)I=I+1
    J=I+1
    IF(I.GT.N)GO TO 20
    IF(J.GT.N) GO TO 30
    IF(MOD(J,L).EQ.0)J=J+1
    K=J+1
    IF(J.GT.N)GO TO 30
    IF(K.GT.N)GO TO 40
    IF(MOD(K,L).EQ.0)K=K+1
    IF(K.GT.N) GO TO 40
    PRINT*,I,J,K
    I=K+1
    IF(I.LE.N) GO TO 10
20 STOP
30 PRINT*,I
STOP
40 PRINT*,I,J
STOP
END PROGRAM
