PROGRAM HIGHEST_MARK
    INTEGER X,SCORE
    PRINT*,'HOW MANY STUDENTS?'
    READ*,N
    PRINT*,'GIVE SCORES'
    READ*,X
    LAR=X
    I=2
10  READ*,SCORE
    IF(SCORE.GE.LAR)LAR=SCORE
    I=I+1
    IF(I.LE.N)GOTO 10

    PRINT*,"THE HIGHEST MARK IS",LAR
    STOP

END PROGRAM
