PROGRAM CIRCLE_POINTS
    INTEGER X,Y
K=0   !COUNTER FOR POINTS ON THE CIRCLE
X=-7

10  Y=-7
20  IF(X**2+Y**2 .EQ.50)K=K+1 !INCREMENTING K BY 1
    Y=Y+1
    IF(Y.LE.7)GOTO 20
    X=X+1
    IF(X.LE.7)GOTO 10

PRINT*,'INTEGER POINTS ON THE CIRCLE:',K
END PROGRAM
