PROGRAM SECOND_LARGEST
    INTEGER X,A,B
    PRINT*,"HOW MANY NUMBERS :"
    READ*,N
    PRINT*,"ENTER THE NUMBERS :"

    READ*,A,B
    LAR1=A
    LAR2=B

    I=2
30  IF(LAR1.GE.LAR2)GO TO 10
    LAR=LAR1
    LAR1=LAR2
    LAR2=LAR

10  I=I+1
    IF(I.GT.N)GO TO 20
    READ*,X
    IF(LAR2.GE.X)GO TO 10
    LAR2=X
    GOTO 30

20  PRINT*,"THE LARGEST NUMBER IS :       ",LAR1
    PRINT*,"THE SECOND LARGEST NUMBER IS :",LAR2
    STOP
END PROGRAM