INTEGER SML1,SML2,X,A,B
PRINT*,'HOW MANY NUMBERS?'
READ*,N
PRINT*,"ENTER THE NUMBERS :"
READ*,A,B
SML1=A
SML2=B
I=2

30  IF(SML1.LE.SML2)GO TO 10
    SML=SML1
    SML1=SML2
    SML2=SML

10  I=I+1
    IF(I.GT.N)GO TO 20
    READ*,X
    IF(SML2.LE.X)GO TO 10
    SML2=X
    GO TO 30

20  PRINT*,"THE SMALLEST NUMBER IS :       ",SML1
    PRINT*,"THE SECOND SMALLEST NUMBER IS :",SML2
    STOP
END PROGRAM
