ICOUNTF=0
ICOUNT8=0
SUM=0.0

DO I=1,75
    READ*,SCORE
    IF(SCORE.LT.40)ICOUNTF=ICOUNTF+1
    IF(SCORE.GE.80)ICOUNT8=ICOUNT8+1
    SUM=SUM+SCORE
END DO
AVE=SUM/75.0
PRINT*,"AVERAGE:",AVE
PRINT*,"FAIL:",ICOUNTF
PRINT*,"EQUAL OR OVER 80:",ICOUNT8
STOP
END
