PROGRAM PRIME_DETECT
    INTEGER COUNT
    COUNT=0
    PRINT*,"CHECK IF PRIME:"
    READ*,N
    I=1
    10  IF(MOD(N,I).EQ.0)COUNT=COUNT+1
        I=I+1
        IF(I.LE.N)GOTO 10
    
    IF (COUNT.EQ.2)THEN
        PRINT*,"PRIME NUMBER"
    ELSE
        PRINT*,"NOT PRIME NUMBER"
    END IF

    STOP
END PROGRAM
