PROGRAM POINT_NUMBERS
    INTEGER COUNT
    COUNT=0  !(INITIALIZING A COUNTER FOR COUNTING POINTS INSIDE THE ELLIPSE 2X^2+3Y^2=100)
        DO 100 I=1,15
            X=I-8
            DO 200 J=1,11
                Y=J-6
                IF(2*X**2+3*Y**2.LT.100)COUNT=COUNT+1
            200 CONTINUE
        100 CONTINUE
    
        PRINT*,"NUMBER OF INTEGER POINTS INSIDE THE ELLIPSE IS:",COUNT
        STOP
    END PROGRAM
    
    