!FUNCTION SUBPROGRAM
FUNCTION ADDS(J,K)
    ADDS=0.0
    IF(J.GT.K)RETURN
    IF(J.LT.K) THEN
        ADDS=0.0
        DO 10 I=0,K
            ADDS=ADDS+(1.0/(J+I))
        10 CONTINUE
    END IF
RETURN
END 

!MAIN PROGRAM
PRINT*,"ENTER VALUE:"
READ*,M,N
RESULT=ADDS(M,N)
PRINT*,"THE SUM IS:",RESULT
STOP
END 

