!SUBROUTINE SUBPROGRAM
SUBROUTINE ADDS(J,K,SUM)
    SUM=0.0
    IF(J.GT.K)RETURN
    IF(J.LT.K) THEN
        DO 10 I=0,K
            SUM=SUM+(1.0/(J+I))
        10 CONTINUE
    END IF
RETURN
END 

!MAIN PROGRAM
PRINT*,"ENTER VALUE:"
READ*,M,N
CALL ADDS(M,N,RESULT)
PRINT*,RESULT
STOP
END 

