FUNCTION FACT(K)
    FACT=1
    IF(K.EQ.0) RETURN
    DO I=1,K
        FACT=FACT*I
    END DO
    RETURN
    END

PRINT*,"WHICH NUMBER FACTORIAL?"
READ*,N
PRINT*,"FATORIAL OF",N,"IS:",FACT(N)
STOP
END