PROGRAM SCORES
INTEGER FAIL
FAIL=0
IGR=0
SUM=0.0
PRINT*,"GIVE SCORES:"
DO 100  I=1,5
        READ*,SCORE
        IF(SCORE.LT.40.0)FAIL=FAIL+1
        IF(SCORE.GE.80.0)IGR=IGR+1
        SUM=SUM+SCORE
    100 CONTINUE
    AVE=SUM/75.0
    PRINT*,"AVERAGE SCORE:",AVE
    PRINT*,"NUMBER OF FAILS:",FAIL
    PRINT*,"WHO SCORED >=80:",IGR
    STOP
END PROGRAM