FUNCTION FACT(K)
FACT=1
IF(K.EQ.0) RETURN
DO I=1,K
    FACT=FACT*I
END DO
RETURN
END

!!MAIN FUNCTION
PROGRAM SUM_SERIES_FACT
SUM=0.0
PRINT*,"SUM UP TO HOW MANY TERMS?"
READ*,N
DO I=1,N
    SUM=SUM+(1.0/FACT(I))
END DO
WRITE(*,20)SUM
20 FORMAT(1X,"THE SUM OF THE SERIES IS",1X,F10.3)
STOP
END PROGRAM