PROGRAM STUDENTS_NUMBER
INTEGER SCORE,COUNT
DIMENSION SCORE(25)
COUNT=0
SUM=0.0
PRINT*,"WHAT ARE THE SCORES?"
DO I=1,25
    READ*,SCORE(I)
    SUM=SUM+SCORE(I)
END DO
AVR=SUM/I
DO I=1,25
    IF(SCORE(I).LT.AVR)COUNT=COUNT+1
END DO

WRITE(*,10)AVR
10 FORMAT(1X,F8.1)
PRINT*,"BELOW AVERAGE:",COUNT
STOP
END
