PROGRAM GRADE_CARD
    INTEGER TEST,PERFECT,ATTEN
    CHARACTER GRADE
    I=1      !INITIALIZE STUDENT COUNTER
    PRINT*,"HOW MANY STUDENTS?"
    READ*,N
    PERFECT=0
    ATTEN=0

100     PRINT*,"ID:",I," & NUMBER OF THE TEST BELOW:"
        READ*,TEST
        IF(TEST.GE.0)ATTEN=ATTEN+1
        IF(TEST.EQ.100)PERFECT=PERFECT+1

        IF(TEST.GE.90)GRADE="A"
        IF(TEST.GE.80.AND.TEST.LT.90)GRADE="B"
        IF(TEST.GE.70.AND.TEST.LT.80)GRADE="C"
        IF(TEST.GE.60.AND.TEST.LT.70)GRADE="D"
        IF(TEST.GE.40.AND.TEST.LT.60)GRADE="E"
        IF(TEST.LT.40)GRADE="F"

        PRINT*,"THE GRADE OF THE ID:",I,"IS:",GRADE
        I=I+1
        IF(I.LE.N)GOTO 100
        
    PRINT*,"STUDENT ATTENDED:",ATTEN
    PRINT*,"NUMBER OF PERFECT PAPERS:",PERFECT
STOP
END PROGRAM

