PROGRAM PLUS_MINUS
    PRINT*,'HOW MANY TERMS?'
    READ*,N
    SUM=0
    I=1
10  SUM=SUM+(((-1.0)**(I-1))*(1.0/I))
    I=I+1
    IF(I.LE.N)GOTO 10

    PRINT*,'THE SUM OF THE ALTERNATING SERIES IS:',SUM
    STOP
END PROGRAM