PROGRAM SEQUENCE_MULTIPLY

    !CHAPTER 4 4.30 PAGE 109

    REAL MULTIPLE,I,N
    MULTIPLE=1.0
    I=1.0

    PRINT*,"VALUE OF N?"
    READ*,N
    IF(N.LT.1.0) GOTO 100

200     MULTIPLE=MULTIPLE*((2.0*I-1.0)/I**2)
        I=I+1.0
        IF(I.LE.N)GOTO 200
        WRITE(*,300) MULTIPLE
        300 FORMAT(F10.5)
        STOP

100     PRINT*, "INVALID VALUE OF N"
        STOP
END PROGRAM