PROGRAM DIVISIBLE_BY_N
    !THIS IS A PROGRAM THAT PRINTS DIVISOR OF N

    PRINT*, "WHAT IS THE NUMBER?"
    READ*,N
    IF(N.LT.10.AND.N.GT.1000)GOTO 100
    PRINT*,"DIVISORS OF",N
   
    !INITIALIZING COUNTERS
        I=1

200     IF(MOD(N,I).EQ.0) PRINT*,I
        I=I+1
        IF(I.LE.N) GOTO 200
        STOP

100     PRINT*,"INVALID VALUE OF INTEGER"
        STOP

END PROGRAM
